# Generated by Django 3.0.2 on 2020-02-18 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default=datetime.datetime(2020, 2, 18, 11, 29, 43, 328946, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
