# Generated by Django 3.0.2 on 2020-02-20 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_summary',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
