# Generated by Django 3.0.2 on 2020-02-20 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_short_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='short_summary',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='summary',
            new_name='headline',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='reporter',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tite',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='article',
            name='date_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=67),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=45),
        ),
    ]
